### PR TITLE
Removes dependency with ext:form as it may be not installed

### PR DESCRIPTION
**Pull request by jmverges**
At the moment you must have installed ext:forms which seems out of the scope of the main purpose of the extension

### CODE REVIEW

**Comment by baschte** [comment]
Hey @jmverges, yeah you're totally right! 
It will be merged and released soon. Thx for your PR. 👍

**Comment by jmverges** [comment]
Hey @baschte neat extension, I like it

**Comment by baschte** [comment]
hey @jmverges,
the new version 1.0.3 is out without the ext:form dependency. I just removed a few lines more as in your PR and then everything was fine again.

**Comment by edekowalski** [comment]
Unbenannt

I get under TYPO3 8, the following error message when I click on a content item. Best thanks, Ede

**Comment by baschte** [comment]
Oh thx for the hint. 👍🏻
I‘ll check that later and fix it.

**Comment by baschte** [comment]
@edekowalski check out the new version 1.0.4 of content_animations. 
NOW with TYPO3 8 LTS. Hope it works now in your project. If not pls let me know.

Cheers 🍻😄

**Comment by edekowalski** [comment]
Tested with Boostrap Package on TYPO3 8, it work's fine!!

Thx cool Extension!!

Best Regard's
Eric

**Pull request merged**
