### PR TITLE
[FEATURE] Toggle to shutdown the automatic append of Animation tab to all CTypes

### PR DESCRIPTION
**Pull request by jmverges**
What do you think?

### CODE REVIEW

**Comment by baschte** [comment]
@jmverges It could be a very nice feature but what would you do if you select that option (removed it from all CTypes) and then you want to add the animation tab to 6 core elements? Overwrite every CType "showitem" property and add it manually? I think that would be very complicated for all integrators and not "fluid", you know? :-D 

What do you think? :-)

**Comment by baschte** [comment]
@jmverges 
The other way it works is to do the opposite. Remove the tab only on specific CTypes. 

Now you can do it in pageTS for "textpic" for example:
`TCEFORM.tt_content.tx_content_animations_animation.types.textpic.disabled=1
TCEFORM.tt_content.tx_content_animations_duration.types.textpic.disabled=1
TCEFORM.tt_content.tx_content_animations_delay.types.textpic.disabled=1`

**Comment by jmverges** [comment]
To complicated for the integrator, thats why by default is added, but for some other use cases could be useful for developers

**Comment by baschte** [comment]
@jmverges why would you remove the animation tab for all CTypes? So what's the usecase for you? When it will needed for you as a developer? 

If i don't want the tab on any CType whats the difference between the setting is disabled and if i deinstall the extension complete?

**Comment by jmverges** [comment]
I tend to have my own custom definition for content elements instead of the ones provides by default in ext:frontend extension. I simply prefer to integrate manually the fields in a different tab and show them if the this extension is installed.

**Comment by baschte** [comment]
Hi @jmverges,
the new version 1.2.0 of content_animations is available with some enhancements and the setting to disable the auto append of the Animation tab. Have fun with it and thx for your PR 😁🍻

**Pull request closed without merging**
